name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    tags:
      - '**'
  release:
    types:
      - published

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: strangelove-ventures/heighliner-build-action@v1.0.0
        with:
          platform: linux/arm64,linux/amd64
          # heighliner chains.yml
          name: persistencecore
          github-organization: persistenceOne
          github-repo: persistenceCore
          dockerfile: cosmos
          registry: docker.io/ajeetgoyal
          go-version: 1.21
          build-target: make install
          binaries: |
            - /go/bin/persistenceCore
          build-env: |
            - LEDGER_ENABLED=false
            - BUILD_TAGS=muslc
